knoerden/blueprints/frontpage.py
import datetime

from flask import Blueprint, render_template
# from lib.database import db

blueprint = Blueprint("frontpage", __name__)

@blueprint.route("/")
def frontpage():
    # print(db)
    about_knoerden = dict(headline="Om K-Nørden",
                          summary='K-Nørden er en forening for børn og unge hvor vi leger med elektronik, programmering og "nørderi"',
                          author="K-Nørden",
                          date=datetime.datetime.now(),
                          url="/",
                          image="static/images/stock/20180418_203511.jpg")
    about_fdf = dict(headline="Om FDF",
                     summary="FDF handler om fælleskab. Gennem lege, hygge, aktiviteter og meget andet møder vi børn og unge",
                     author="K-Nørden",
                     date=datetime.datetime.now(),
                     url="https://fdf.dk/om-fdf/hvad-er-fdf/",
                     image="static/images/stock/20180418_203511.jpg")
    about_k19 = dict(headline="Om K19 - Vanløse",
                     summary="K-Nørden er et projekt i FDF K19 - Vanløse som er en af landets største kredse. Du bliver dermed en del af et meget størrere fælleskab.",
                     author="K-Nørden",
                     date=datetime.datetime.now(),
                     url="http://fdfk19.dk",
                     image="static/images/stock/20180418_203511.jpg")
    items = ([about_knoerden, about_fdf, about_k19] +
             [dict(headline="foo", summary="Foo bar baz bar", author="me", date=datetime.datetime.now(), url="/", image="static/images/test100x100.png") for _ in range(10)])
    # items[2]["summary"] = "bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla " "bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla "
    # items[2]["headline"] = "Om KN"
    items[2]["image"] = "static/images/stock/20180418_203511.jpg"

    items[5]["summary"] = "bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla " "bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla "
    items[5]["headline"] = "Om KN"

    return render_template("frontpage.html", items=items)

knoerden/blueprints/meetings.py
import datetime
import re
import itertools

from flask import Blueprint, render_template, request, redirect, url_for, session
from knoerden.lib.utils import request_data, abort
from knoerden.lib import database

blueprint = Blueprint("meetings", __name__, url_prefix="/meetings/")

@blueprint.route("/")
def list():
    meetings = database.execute("select * from meetings order by date asc")
    meetings_by_year = itertools.groupby(meetings, key=lambda meeting: meeting.date.year)
    return render_template("meetings.html", meetings_by_year=meetings_by_year)


@blueprint.route("meeting/<int:meeting_id>/", methods=["GET", "POST"])
def meeting(meeting_id):
    if request.method == "POST":
        data = request_data()
        data.x
        if data.is_attending == "yes":
            is_attending = True
        elif data.is_attending == "no":
            is_attending = False
        else:
            raise Exception("Unknown input for is_attending {}".format(data.is_attending))

        with database.transaction() as transaction:
            transaction.execute("delete from meetings_users where meeting_id = ? and user_id = ?", meeting_id, session["user_id"])
            transaction.create("meetings_users", meeting_id=meeting_id, user_id=session["user_id"], is_attending=data.is_attending, note=data.note)
    meeting = database.execute("select * from meetings where meeting_id = ?", meeting_id).one()
    users = database.execute("select * from meetings_users inner join users using (user_id) where meeting_id = ?", meeting_id)
    number_of_attending = sum(1 for x in users if x.is_attending)
    return render_template("meeting.html", meeting=meeting, users=users, number_of_attending=number_of_attending)


@blueprint.route("add/", methods=["GET", "POST"])
def add():
    if request.method == "GET":
        return render_template("meetings_add.html")
    if request.method == "POST":
        data = request_data()
        date = datetime.datetime.strptime(data.date, "%Y-%m-%d") # eg: Tue, 22 Nov 2011 06:00:00 GMT"
        time_parts = re.split(" *[.,:;] *", data.time.strip())
        if len(time_parts) == 1:
            hour = time_parts[0]
            minute = 0
        elif len(time_parts) == 2:
            hour = time_parts[0]
            minute = time_parts[1]
        else:
            abort(f"Invalid time format: {data.time}")
        try:
            date = date.replace(hour=int(hour), minute=int(minute))
        except Exception:
            abort(f"Invalid time format: {data.time}")
        meeting = database.create("Meetings",
                                  date=date,
                                  title=data.title,
                                  description=data.description,
                                  created_by=session["user_id"])
        return redirect(url_for("meetings.list"))

knoerden/blueprints/users.py
from flask import Blueprint, render_template, request, redirect, url_for
from knoerden.lib import database, config
from knoerden.lib.user import password_check, authenticate, unauthenticate
from knoerden.lib.utils import request_data, abort

blueprint = Blueprint("users", __name__, url_prefix="/users/")

@blueprint.route("login/", methods=["POST"])
def login():
    data = request_data()
    print(data)
    users = database.execute("select user_id, username, password, is_deleted from Users inner join Passwords using (user_id) where lower(username) = ?", data.username.lower())
    print(users)
    user = users.one(error="Invalid username")
    if user.is_deleted:
        abort("User is deleted")
    if not password_check(data.password, user.password):
        abort("Invalid password")
    authenticate(user)
    return redirect(request.referrer)

@blueprint.route("logout/")
def logout():
    unauthenticate()
    return redirect(url_for("frontpage.frontpage"))

knoerden/templates/frontpage.html
{% extends "layout.html" %}

{% block elements %}
{% for item in items %}
<div class="element">
  <div class="element-aspect">
    <a class="element-content notched" href="{{item['url']}}">
      {% if item["image"] %}
      <img class="element-image" src="{{item['image']}}"/>
      {% endif %}
      <div class="element-description">
        <div class="element-headline">{{item["headline"]}}</div>
        <div class="element-byline">{{item["author"]}} - {{item["date"]}}</div>
        <div class="element-summary">{{item["summary"]}}</div>
      </div>
    </a>
  </div>
</div>
{% endfor %}
Hello, World from html2
{% endblock %}

knoerden/templates/layout.html
<!doctype html>
<html lang="da">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="content-language" content="da" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <title>K-Nørden</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css"/>

    <script src="/static/libs/jquery-3.3.1.min.js"></script>
    <script src="/static/libs/jquery-ui-1.12.1.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
    <!-- <script src="https://unpkg.com/fea2ther-icons/dist/feather.min.js"></script> -->

    <script src="/static/knoerden.js"></script>
  </head>
  <body>
    <nav class="menubar">
      <!-- <a href=''><div><i style="float:left; width:16px;" data-feather="settingsu"></i>Forside</div></a> -->
      <a href="/"><div>Forside</div></a>
      <a href="/wiki"><div>Wiki</div></a>
      <a href="/projects"><div>Projekter</div></a>
      <a href="/inventory"><div>Lager</div></a>
      <a href="{{url_for('meetings.list')}}"><div>Møder</div></a>
      <a href=""><div>Om K-Nørden</div></a>
      <span></span>
      <!-- <a></a> -->
      <!-- <a></a> -->

      {% if session["username"] %}
      logged in as {{session["username"]}}
      {% else %}
      <a href='' class="rightt" id="login_btn"><div>Login</div></a>
      {% endif %}
    </nav>

    <div class="modal" id="login">
      <form class="modal-content animate notched" action='{{url_for("users.login")}}' method="post">
        <span class="close" title="Luk">&times;</span>
        <div class="input-group">
          <div class="input-group-header">U</div>
          <input type="text" placeholder="Brugernavn / medlemsnummer" name="username" required/>
        </div>
        <div class="input-group">
          <div class="input-group-header">U</div>
          <input type="password" placeholder="password" name="password" required/>
        </div>
        <div style="display:flex; justify-content: space-between">
          <div><a href=''>Glemt login?</a></div>
          <button type="submit">Login</button>
        </div>
      </form>
    </div>
    <div class="elements">
      {% block elements %}{% endblock %}
    </div>
    <div class="page">
      {% block page %}{% endblock %}
    </div>
  </body>
  <script>
    <!-- feather.replace(); -->
  </script>
</html>

knoerden/templates/meeting.html
{% extends "layout.html" %}

{% block page %}
<div class="meeting-bar">
  <span class="meeting-title">{{meeting.title}}</span>
  <span class="meeting-date">{{meeting.date | date}}</span>
</div>
<div class="meeting-subbar">
  <span>{{meeting.created_at | date}}</span>
  <span>{{meeting.created_by | fetch_user}}</span>
</div>
{% if meeting.is_canceled %}
<div class="meeting-canceled">Aflyst</div>
{% endif %}
<form method="POST">
  <label for="is_attending-yes">Kommer</label>
  <input type="radio" name="is_attending" value="yes" id="is_attending-yes"/>
  <label for="is_attending-no">Kommer Ikke</label>
  <input type="radio" name="is_attending" value="no" id="is_attending-no"/>
  <input type="text" name="note" placeholder="Note"/>
  <button type="submit">Gem</button>
</form>
<div>
  {{meeting.description}}
</div>
<table class="meeting-table">
  <tr>
    <th>Bruger</th>
    <th>Kommer</th>
    <th>Note</th>
  </tr>
{% for user in users %}
  <tr>
    <td class="meeting-table-user">{{user | user}}</td>
    <td class="meeting-table-is_attending">{{user.is_attending}}</td>
    <td class="meeting-table-note">{{user.note}}</td>
  </tr>
{% endfor %}
Kommer: {{number_of_attending}}

</table>

{% endblock %}

knoerden/templates/meetings.html
{% extends "layout.html" %}

{% block page %}
<div>
  {% for year, meetings in meetings_by_year %}
  <h1>{{year}}</h1>
  <table>
    {% for meeting in meetings %}
    <tr>
      <td>{{meeting.date | date}}</td>
      <td>
        <a href="{{url_for('meetings.meeting', meeting_id=meeting.meeting_id)}}">
          {{meeting.title}}
        </a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% endfor %}
</div>
{% endblock %}

knoerden/templates/meetings_add.html
{% extends "layout.html" %}

{% block page %}
Opret møde
<div>
  <form method="POST">
    <div class="input-group">
      <div class="input-group-header">Dato</div>
      <input name="date" type="date"/>
    </div>
    <div class="input-group">
      <div class="input-group-header">Tidspunkt</div>
      <input name="time" type="text" value="18:00"/>
    </div>
    <div class="input-group">
      <div class="input-group-header">Titel</div>
      <input name="title" type="text"/>
    </div>
    <div class="input-group">
      <textarea name="description"></textarea>
    </div>
    <button type="submit">Opret</button>
  </form>
</div>
{% endblock %}